# Generated by Django 4.1.2 on 2022-10-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_artiste_age_alter_artiste_artiste_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
