# Generated by Django 4.1.2 on 2022-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_song_id_song_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.CharField(default=0, max_length=25, primary_key=True, serialize=False),
        ),
    ]
