# Generated by Django 4.1.2 on 2022-10-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_artiste_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
