# Generated by Django 4.1.2 on 2022-10-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_remove_song_id_song_song_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_id',
        ),
        migrations.AddField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, default='Null', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
